### ISSUE TITLE
Add l10n

### ISSUE THREAD

**Issue by vinzv** [simopil/SUSEPrimeQt#1]
If you can find the time it'd be great to have l10n implemented. I'd volunteer for translating to German.

**Comment by simopil** [comment]
Yes, as soon as possible I'll look how-to-do this (I'm totally new to QT). I can translate it in Italian too

**Comment by vinzv** [comment]
Yeah, cool! No pressure though! ;-)

**Comment by simopil** [comment]
I added sort of localization that reads system locale and apply language if exists.
Also must be add  <file>lang/xx_XX.qm</file> in translations.qrc

**Comment by Tarbetu** [comment]
I'm willing to translate for Turkish. How can I help?

**Comment by vinzv** [comment]
> I'm willing to translate for Turkish. How can I help?

Clone the repo, copy one of the language files e.g. https://github.com/simopil/SUSEPrimeQt/blob/master/src/lang/de_DE.ts and rename it to tr_TR.ts. Afterwards just remove the German translations and add the Turkish ones.

If you need help, just ping here! :)

**Comment by Tarbetu** [comment]
I have sent a pull request for you. I am who is kind of a git noob, I hope I did not have any mistake :)

**Comment by vinzv** [comment]
Looks perfectly fine, though I don't know any Turkish. :-)
So we just need to wait for @simopil to accept the PR.

**Comment by Tarbetu** [comment]
I hope @simopil thinks same with you. :)
